spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/oauth2-dummy-api?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 
    jpa:
      hibernate:
        ddl-auto: none
    thymeleaf:
      cache: false
    output:
      ansi:
        enabled: always
        
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: client-id
                        clientSecret: client-secret
                        redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - email
                            - profile
                    github:
                        clientId: client-id
                        clientSecret: client-secret
                        redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - user:email
                            - read:user
                    eivas:
                        clientId: da34bd0192222531d60922e683181475.PVA.eiv.com.ar
                        clientSecret: cb5b45aff40851363b2cb26214fd25c9
                        redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
                        scope:
                            - email
                            - profile
                        client-name: Eiv AS
                        provider: eivas
                        client-authentication-method: basic
                        authorization-grant-type: authorization_code
                
                provider:
                    eivas:
                        authorization-uri: http://eq016:8081/oauth/authorize
                        token-uri: http://eq016:8081/oauth/token
                        user-info-uri: http://eq016:8081/me
                        user-name-attribute: username
