spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/oauth2-dummy-api
        username: root
        password: 
    jpa:
      hibernate:
        ddl-auto: none
    thymeleaf:
      cache: false
    output:
      ansi:
        enabled: always